// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: entropy/ml/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgGenerate struct {
	Creator   string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Modality  string `protobuf:"bytes,2,opt,name=modality,proto3" json:"modality,omitempty"`
	Model     string `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	Prompt    string `protobuf:"bytes,4,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Negprompt string `protobuf:"bytes,5,opt,name=negprompt,proto3" json:"negprompt,omitempty"`
	Seed      string `protobuf:"bytes,6,opt,name=seed,proto3" json:"seed,omitempty"`
	Machine   string `protobuf:"bytes,7,opt,name=machine,proto3" json:"machine,omitempty"`
}

func (m *MsgGenerate) Reset()         { *m = MsgGenerate{} }
func (m *MsgGenerate) String() string { return proto.CompactTextString(m) }
func (*MsgGenerate) ProtoMessage()    {}
func (*MsgGenerate) Descriptor() ([]byte, []int) {
	return fileDescriptor_95773e52598ef606, []int{0}
}
func (m *MsgGenerate) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgGenerate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgGenerate.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgGenerate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgGenerate.Merge(m, src)
}
func (m *MsgGenerate) XXX_Size() int {
	return m.Size()
}
func (m *MsgGenerate) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgGenerate.DiscardUnknown(m)
}

var xxx_messageInfo_MsgGenerate proto.InternalMessageInfo

func (m *MsgGenerate) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgGenerate) GetModality() string {
	if m != nil {
		return m.Modality
	}
	return ""
}

func (m *MsgGenerate) GetModel() string {
	if m != nil {
		return m.Model
	}
	return ""
}

func (m *MsgGenerate) GetPrompt() string {
	if m != nil {
		return m.Prompt
	}
	return ""
}

func (m *MsgGenerate) GetNegprompt() string {
	if m != nil {
		return m.Negprompt
	}
	return ""
}

func (m *MsgGenerate) GetSeed() string {
	if m != nil {
		return m.Seed
	}
	return ""
}

func (m *MsgGenerate) GetMachine() string {
	if m != nil {
		return m.Machine
	}
	return ""
}

type MsgGenerateResponse struct {
}

func (m *MsgGenerateResponse) Reset()         { *m = MsgGenerateResponse{} }
func (m *MsgGenerateResponse) String() string { return proto.CompactTextString(m) }
func (*MsgGenerateResponse) ProtoMessage()    {}
func (*MsgGenerateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_95773e52598ef606, []int{1}
}
func (m *MsgGenerateResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgGenerateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgGenerateResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgGenerateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgGenerateResponse.Merge(m, src)
}
func (m *MsgGenerateResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgGenerateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgGenerateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgGenerateResponse proto.InternalMessageInfo

type MsgInpaint struct {
	Creator   string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Model     string `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	Image     string `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	Mask      string `protobuf:"bytes,4,opt,name=mask,proto3" json:"mask,omitempty"`
	Prompt    string `protobuf:"bytes,5,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Negprompt string `protobuf:"bytes,6,opt,name=negprompt,proto3" json:"negprompt,omitempty"`
	Seed      string `protobuf:"bytes,7,opt,name=seed,proto3" json:"seed,omitempty"`
	Machine   string `protobuf:"bytes,8,opt,name=machine,proto3" json:"machine,omitempty"`
}

func (m *MsgInpaint) Reset()         { *m = MsgInpaint{} }
func (m *MsgInpaint) String() string { return proto.CompactTextString(m) }
func (*MsgInpaint) ProtoMessage()    {}
func (*MsgInpaint) Descriptor() ([]byte, []int) {
	return fileDescriptor_95773e52598ef606, []int{2}
}
func (m *MsgInpaint) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgInpaint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgInpaint.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgInpaint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgInpaint.Merge(m, src)
}
func (m *MsgInpaint) XXX_Size() int {
	return m.Size()
}
func (m *MsgInpaint) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgInpaint.DiscardUnknown(m)
}

var xxx_messageInfo_MsgInpaint proto.InternalMessageInfo

func (m *MsgInpaint) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgInpaint) GetModel() string {
	if m != nil {
		return m.Model
	}
	return ""
}

func (m *MsgInpaint) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *MsgInpaint) GetMask() string {
	if m != nil {
		return m.Mask
	}
	return ""
}

func (m *MsgInpaint) GetPrompt() string {
	if m != nil {
		return m.Prompt
	}
	return ""
}

func (m *MsgInpaint) GetNegprompt() string {
	if m != nil {
		return m.Negprompt
	}
	return ""
}

func (m *MsgInpaint) GetSeed() string {
	if m != nil {
		return m.Seed
	}
	return ""
}

func (m *MsgInpaint) GetMachine() string {
	if m != nil {
		return m.Machine
	}
	return ""
}

type MsgInpaintResponse struct {
}

func (m *MsgInpaintResponse) Reset()         { *m = MsgInpaintResponse{} }
func (m *MsgInpaintResponse) String() string { return proto.CompactTextString(m) }
func (*MsgInpaintResponse) ProtoMessage()    {}
func (*MsgInpaintResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_95773e52598ef606, []int{3}
}
func (m *MsgInpaintResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgInpaintResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgInpaintResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgInpaintResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgInpaintResponse.Merge(m, src)
}
func (m *MsgInpaintResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgInpaintResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgInpaintResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgInpaintResponse proto.InternalMessageInfo

type MsgCtrl struct {
	Creator   string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Model     string `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	Ctrlmodel string `protobuf:"bytes,3,opt,name=ctrlmodel,proto3" json:"ctrlmodel,omitempty"`
	Image     string `protobuf:"bytes,4,opt,name=image,proto3" json:"image,omitempty"`
	Prompt    string `protobuf:"bytes,5,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Negprompt string `protobuf:"bytes,6,opt,name=negprompt,proto3" json:"negprompt,omitempty"`
	Seed      string `protobuf:"bytes,7,opt,name=seed,proto3" json:"seed,omitempty"`
	Machine   string `protobuf:"bytes,8,opt,name=machine,proto3" json:"machine,omitempty"`
}

func (m *MsgCtrl) Reset()         { *m = MsgCtrl{} }
func (m *MsgCtrl) String() string { return proto.CompactTextString(m) }
func (*MsgCtrl) ProtoMessage()    {}
func (*MsgCtrl) Descriptor() ([]byte, []int) {
	return fileDescriptor_95773e52598ef606, []int{4}
}
func (m *MsgCtrl) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCtrl) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCtrl.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCtrl) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCtrl.Merge(m, src)
}
func (m *MsgCtrl) XXX_Size() int {
	return m.Size()
}
func (m *MsgCtrl) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCtrl.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCtrl proto.InternalMessageInfo

func (m *MsgCtrl) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgCtrl) GetModel() string {
	if m != nil {
		return m.Model
	}
	return ""
}

func (m *MsgCtrl) GetCtrlmodel() string {
	if m != nil {
		return m.Ctrlmodel
	}
	return ""
}

func (m *MsgCtrl) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *MsgCtrl) GetPrompt() string {
	if m != nil {
		return m.Prompt
	}
	return ""
}

func (m *MsgCtrl) GetNegprompt() string {
	if m != nil {
		return m.Negprompt
	}
	return ""
}

func (m *MsgCtrl) GetSeed() string {
	if m != nil {
		return m.Seed
	}
	return ""
}

func (m *MsgCtrl) GetMachine() string {
	if m != nil {
		return m.Machine
	}
	return ""
}

type MsgCtrlResponse struct {
}

func (m *MsgCtrlResponse) Reset()         { *m = MsgCtrlResponse{} }
func (m *MsgCtrlResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCtrlResponse) ProtoMessage()    {}
func (*MsgCtrlResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_95773e52598ef606, []int{5}
}
func (m *MsgCtrlResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCtrlResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCtrlResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCtrlResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCtrlResponse.Merge(m, src)
}
func (m *MsgCtrlResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCtrlResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCtrlResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCtrlResponse proto.InternalMessageInfo

type MsgLanguage struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Model   string `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	Body    string `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
}

func (m *MsgLanguage) Reset()         { *m = MsgLanguage{} }
func (m *MsgLanguage) String() string { return proto.CompactTextString(m) }
func (*MsgLanguage) ProtoMessage()    {}
func (*MsgLanguage) Descriptor() ([]byte, []int) {
	return fileDescriptor_95773e52598ef606, []int{6}
}
func (m *MsgLanguage) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgLanguage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgLanguage.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgLanguage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgLanguage.Merge(m, src)
}
func (m *MsgLanguage) XXX_Size() int {
	return m.Size()
}
func (m *MsgLanguage) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgLanguage.DiscardUnknown(m)
}

var xxx_messageInfo_MsgLanguage proto.InternalMessageInfo

func (m *MsgLanguage) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgLanguage) GetModel() string {
	if m != nil {
		return m.Model
	}
	return ""
}

func (m *MsgLanguage) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type MsgLanguageResponse struct {
}

func (m *MsgLanguageResponse) Reset()         { *m = MsgLanguageResponse{} }
func (m *MsgLanguageResponse) String() string { return proto.CompactTextString(m) }
func (*MsgLanguageResponse) ProtoMessage()    {}
func (*MsgLanguageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_95773e52598ef606, []int{7}
}
func (m *MsgLanguageResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgLanguageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgLanguageResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgLanguageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgLanguageResponse.Merge(m, src)
}
func (m *MsgLanguageResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgLanguageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgLanguageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgLanguageResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgGenerate)(nil), "blockentropy.entropy.ml.MsgGenerate")
	proto.RegisterType((*MsgGenerateResponse)(nil), "blockentropy.entropy.ml.MsgGenerateResponse")
	proto.RegisterType((*MsgInpaint)(nil), "blockentropy.entropy.ml.MsgInpaint")
	proto.RegisterType((*MsgInpaintResponse)(nil), "blockentropy.entropy.ml.MsgInpaintResponse")
	proto.RegisterType((*MsgCtrl)(nil), "blockentropy.entropy.ml.MsgCtrl")
	proto.RegisterType((*MsgCtrlResponse)(nil), "blockentropy.entropy.ml.MsgCtrlResponse")
	proto.RegisterType((*MsgLanguage)(nil), "blockentropy.entropy.ml.MsgLanguage")
	proto.RegisterType((*MsgLanguageResponse)(nil), "blockentropy.entropy.ml.MsgLanguageResponse")
}

func init() { proto.RegisterFile("entropy/ml/tx.proto", fileDescriptor_95773e52598ef606) }

var fileDescriptor_95773e52598ef606 = []byte{
	// 462 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x94, 0xcf, 0x6f, 0xd3, 0x30,
	0x14, 0xc7, 0xeb, 0x2e, 0x6d, 0xda, 0xc7, 0x01, 0xe1, 0x15, 0x88, 0xaa, 0x29, 0x9a, 0x0a, 0x87,
	0x09, 0x50, 0x2a, 0xc1, 0x7f, 0x00, 0x48, 0x08, 0x89, 0x1e, 0xe8, 0x11, 0xa4, 0x49, 0x6e, 0x6a,
	0x79, 0xd1, 0x62, 0x3b, 0xb2, 0x3d, 0x69, 0xfd, 0x2f, 0xf8, 0x87, 0xb8, 0x23, 0x4e, 0xe3, 0xc6,
	0x11, 0xb5, 0xff, 0x03, 0x67, 0x14, 0xcf, 0x76, 0x02, 0xa2, 0x61, 0xbb, 0x70, 0x8a, 0xdf, 0x0f,
	0x3f, 0x7f, 0x3f, 0x2f, 0xcf, 0x86, 0x43, 0x2a, 0x8c, 0x92, 0xd5, 0x66, 0xce, 0xcb, 0xb9, 0xb9,
	0xcc, 0x2a, 0x25, 0x8d, 0xc4, 0x0f, 0x57, 0xa5, 0xcc, 0xcf, 0x5d, 0x24, 0xf3, 0x5f, 0x5e, 0xce,
	0x3e, 0x23, 0xb8, 0xb3, 0xd0, 0xec, 0x0d, 0x15, 0x54, 0x11, 0x43, 0x71, 0x02, 0x71, 0xae, 0x28,
	0x31, 0x52, 0x25, 0xe8, 0x18, 0x9d, 0x8c, 0x97, 0xde, 0xc4, 0x53, 0x18, 0x71, 0xb9, 0x26, 0x65,
	0x61, 0x36, 0x49, 0xdf, 0x86, 0x82, 0x8d, 0x27, 0x30, 0xe0, 0x72, 0x4d, 0xcb, 0xe4, 0xc0, 0x06,
	0xae, 0x0d, 0xfc, 0x00, 0x86, 0x95, 0x92, 0xbc, 0x32, 0x49, 0x64, 0xdd, 0xce, 0xc2, 0x47, 0x30,
	0x16, 0x94, 0xb9, 0xd0, 0xc0, 0x86, 0x1a, 0x07, 0xc6, 0x10, 0x69, 0x4a, 0xd7, 0xc9, 0xd0, 0x06,
	0xec, 0xba, 0x56, 0xc5, 0x49, 0x7e, 0x56, 0x08, 0x9a, 0xc4, 0xd7, 0xaa, 0x9c, 0x39, 0xbb, 0x0f,
	0x87, 0x2d, 0xf9, 0x4b, 0xaa, 0x2b, 0x29, 0x34, 0x9d, 0x7d, 0x45, 0x00, 0x0b, 0xcd, 0xde, 0x8a,
	0x8a, 0x14, 0xc2, 0x74, 0x50, 0x05, 0xe5, 0xfd, 0xb6, 0xf2, 0x09, 0x0c, 0x0a, 0x4e, 0x18, 0xf5,
	0x3c, 0xd6, 0xa8, 0x95, 0x71, 0xa2, 0xcf, 0x1d, 0x8d, 0x5d, 0xb7, 0x18, 0x07, 0xfb, 0x19, 0x87,
	0xfb, 0x18, 0xe3, 0xbf, 0x33, 0x8e, 0x7e, 0x67, 0x9c, 0x00, 0x6e, 0x58, 0x02, 0xe2, 0x37, 0x04,
	0xf1, 0x42, 0xb3, 0x57, 0x46, 0x95, 0xb7, 0xe6, 0x3b, 0x82, 0x71, 0x6e, 0x54, 0xd9, 0xfe, 0x67,
	0x8d, 0xa3, 0xa1, 0x8f, 0xda, 0xf4, 0xff, 0x83, 0xf4, 0x1e, 0xdc, 0x75, 0x48, 0x01, 0xf3, 0xbd,
	0x9d, 0xcf, 0x77, 0x44, 0xb0, 0x8b, 0x5a, 0xc5, 0x6d, 0x49, 0x31, 0x44, 0x2b, 0xb9, 0xde, 0x38,
	0x48, 0xbb, 0x76, 0x33, 0xe3, 0x4b, 0xfa, 0x93, 0x9e, 0xff, 0xec, 0xc3, 0xc1, 0x42, 0x33, 0x7c,
	0x0a, 0xa3, 0x70, 0x1d, 0x1e, 0x67, 0x7b, 0x2e, 0x4e, 0xd6, 0x9a, 0xba, 0xe9, 0xb3, 0x9b, 0x64,
	0xf9, 0x73, 0xf0, 0x47, 0x88, 0xfd, 0x5c, 0x3e, 0xea, 0xda, 0xe8, 0x92, 0xa6, 0x4f, 0x6f, 0x90,
	0x14, 0x8a, 0x2f, 0x21, 0xb2, 0x13, 0x71, 0xdc, 0xb5, 0xa9, 0xce, 0x98, 0x9e, 0xfc, 0x2b, 0x23,
	0xd4, 0x3c, 0x85, 0x51, 0xe8, 0x7f, 0x67, 0x43, 0x7c, 0x56, 0x77, 0x43, 0xfe, 0x6c, 0xfc, 0xcb,
	0xd7, 0x5f, 0xb6, 0x29, 0xba, 0xda, 0xa6, 0xe8, 0xc7, 0x36, 0x45, 0x9f, 0x76, 0x69, 0xef, 0x6a,
	0x97, 0xf6, 0xbe, 0xef, 0xd2, 0xde, 0x87, 0x27, 0xac, 0x30, 0x67, 0x17, 0xab, 0x2c, 0x97, 0x7c,
	0xde, 0xae, 0x38, 0xf7, 0xdf, 0x4b, 0xfb, 0xca, 0x6d, 0x2a, 0xaa, 0x57, 0x43, 0xfb, 0xd2, 0xbd,
	0xf8, 0x15, 0x00, 0x00, 0xff, 0xff, 0x37, 0x13, 0xaf, 0xce, 0x00, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	Generate(ctx context.Context, in *MsgGenerate, opts ...grpc.CallOption) (*MsgGenerateResponse, error)
	Inpaint(ctx context.Context, in *MsgInpaint, opts ...grpc.CallOption) (*MsgInpaintResponse, error)
	Ctrl(ctx context.Context, in *MsgCtrl, opts ...grpc.CallOption) (*MsgCtrlResponse, error)
	Language(ctx context.Context, in *MsgLanguage, opts ...grpc.CallOption) (*MsgLanguageResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) Generate(ctx context.Context, in *MsgGenerate, opts ...grpc.CallOption) (*MsgGenerateResponse, error) {
	out := new(MsgGenerateResponse)
	err := c.cc.Invoke(ctx, "/blockentropy.entropy.ml.Msg/Generate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) Inpaint(ctx context.Context, in *MsgInpaint, opts ...grpc.CallOption) (*MsgInpaintResponse, error) {
	out := new(MsgInpaintResponse)
	err := c.cc.Invoke(ctx, "/blockentropy.entropy.ml.Msg/Inpaint", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) Ctrl(ctx context.Context, in *MsgCtrl, opts ...grpc.CallOption) (*MsgCtrlResponse, error) {
	out := new(MsgCtrlResponse)
	err := c.cc.Invoke(ctx, "/blockentropy.entropy.ml.Msg/Ctrl", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) Language(ctx context.Context, in *MsgLanguage, opts ...grpc.CallOption) (*MsgLanguageResponse, error) {
	out := new(MsgLanguageResponse)
	err := c.cc.Invoke(ctx, "/blockentropy.entropy.ml.Msg/Language", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	Generate(context.Context, *MsgGenerate) (*MsgGenerateResponse, error)
	Inpaint(context.Context, *MsgInpaint) (*MsgInpaintResponse, error)
	Ctrl(context.Context, *MsgCtrl) (*MsgCtrlResponse, error)
	Language(context.Context, *MsgLanguage) (*MsgLanguageResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) Generate(ctx context.Context, req *MsgGenerate) (*MsgGenerateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Generate not implemented")
}
func (*UnimplementedMsgServer) Inpaint(ctx context.Context, req *MsgInpaint) (*MsgInpaintResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Inpaint not implemented")
}
func (*UnimplementedMsgServer) Ctrl(ctx context.Context, req *MsgCtrl) (*MsgCtrlResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ctrl not implemented")
}
func (*UnimplementedMsgServer) Language(ctx context.Context, req *MsgLanguage) (*MsgLanguageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Language not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_Generate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgGenerate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).Generate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blockentropy.entropy.ml.Msg/Generate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).Generate(ctx, req.(*MsgGenerate))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_Inpaint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgInpaint)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).Inpaint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blockentropy.entropy.ml.Msg/Inpaint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).Inpaint(ctx, req.(*MsgInpaint))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_Ctrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCtrl)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).Ctrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blockentropy.entropy.ml.Msg/Ctrl",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).Ctrl(ctx, req.(*MsgCtrl))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_Language_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgLanguage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).Language(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blockentropy.entropy.ml.Msg/Language",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).Language(ctx, req.(*MsgLanguage))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "blockentropy.entropy.ml.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Generate",
			Handler:    _Msg_Generate_Handler,
		},
		{
			MethodName: "Inpaint",
			Handler:    _Msg_Inpaint_Handler,
		},
		{
			MethodName: "Ctrl",
			Handler:    _Msg_Ctrl_Handler,
		},
		{
			MethodName: "Language",
			Handler:    _Msg_Language_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "entropy/ml/tx.proto",
}

func (m *MsgGenerate) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgGenerate) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgGenerate) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Machine) > 0 {
		i -= len(m.Machine)
		copy(dAtA[i:], m.Machine)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Machine)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.Seed) > 0 {
		i -= len(m.Seed)
		copy(dAtA[i:], m.Seed)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Seed)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Negprompt) > 0 {
		i -= len(m.Negprompt)
		copy(dAtA[i:], m.Negprompt)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Negprompt)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Prompt) > 0 {
		i -= len(m.Prompt)
		copy(dAtA[i:], m.Prompt)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Prompt)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Model) > 0 {
		i -= len(m.Model)
		copy(dAtA[i:], m.Model)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Model)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Modality) > 0 {
		i -= len(m.Modality)
		copy(dAtA[i:], m.Modality)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Modality)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgGenerateResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgGenerateResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgGenerateResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgInpaint) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgInpaint) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgInpaint) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Machine) > 0 {
		i -= len(m.Machine)
		copy(dAtA[i:], m.Machine)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Machine)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.Seed) > 0 {
		i -= len(m.Seed)
		copy(dAtA[i:], m.Seed)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Seed)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.Negprompt) > 0 {
		i -= len(m.Negprompt)
		copy(dAtA[i:], m.Negprompt)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Negprompt)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Prompt) > 0 {
		i -= len(m.Prompt)
		copy(dAtA[i:], m.Prompt)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Prompt)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Mask) > 0 {
		i -= len(m.Mask)
		copy(dAtA[i:], m.Mask)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Mask)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Image) > 0 {
		i -= len(m.Image)
		copy(dAtA[i:], m.Image)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Image)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Model) > 0 {
		i -= len(m.Model)
		copy(dAtA[i:], m.Model)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Model)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgInpaintResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgInpaintResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgInpaintResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgCtrl) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCtrl) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCtrl) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Machine) > 0 {
		i -= len(m.Machine)
		copy(dAtA[i:], m.Machine)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Machine)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.Seed) > 0 {
		i -= len(m.Seed)
		copy(dAtA[i:], m.Seed)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Seed)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.Negprompt) > 0 {
		i -= len(m.Negprompt)
		copy(dAtA[i:], m.Negprompt)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Negprompt)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Prompt) > 0 {
		i -= len(m.Prompt)
		copy(dAtA[i:], m.Prompt)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Prompt)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Image) > 0 {
		i -= len(m.Image)
		copy(dAtA[i:], m.Image)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Image)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Ctrlmodel) > 0 {
		i -= len(m.Ctrlmodel)
		copy(dAtA[i:], m.Ctrlmodel)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Ctrlmodel)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Model) > 0 {
		i -= len(m.Model)
		copy(dAtA[i:], m.Model)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Model)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCtrlResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCtrlResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCtrlResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgLanguage) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgLanguage) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgLanguage) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Body) > 0 {
		i -= len(m.Body)
		copy(dAtA[i:], m.Body)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Body)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Model) > 0 {
		i -= len(m.Model)
		copy(dAtA[i:], m.Model)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Model)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgLanguageResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgLanguageResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgLanguageResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgGenerate) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Modality)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Model)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Prompt)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Negprompt)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Seed)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Machine)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgGenerateResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgInpaint) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Model)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Image)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Mask)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Prompt)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Negprompt)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Seed)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Machine)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgInpaintResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgCtrl) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Model)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Ctrlmodel)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Image)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Prompt)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Negprompt)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Seed)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Machine)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgCtrlResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgLanguage) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Model)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Body)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgLanguageResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgGenerate) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgGenerate: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgGenerate: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Modality", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Modality = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Model", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Model = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Prompt", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Prompt = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Negprompt", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Negprompt = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Seed", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Seed = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Machine", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Machine = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgGenerateResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgGenerateResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgGenerateResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgInpaint) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgInpaint: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgInpaint: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Model", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Model = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Image", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Image = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Mask", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Mask = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Prompt", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Prompt = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Negprompt", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Negprompt = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Seed", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Seed = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Machine", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Machine = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgInpaintResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgInpaintResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgInpaintResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCtrl) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCtrl: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCtrl: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Model", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Model = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ctrlmodel", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Ctrlmodel = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Image", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Image = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Prompt", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Prompt = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Negprompt", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Negprompt = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Seed", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Seed = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Machine", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Machine = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCtrlResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCtrlResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCtrlResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgLanguage) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgLanguage: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgLanguage: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Model", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Model = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Body", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Body = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgLanguageResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgLanguageResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgLanguageResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
