// Generated by Ignite ignite.com/cli

import { StdFee } from "@cosmjs/launchpad";
import { SigningStargateClient, DeliverTxResponse } from "@cosmjs/stargate";
import { EncodeObject, GeneratedType, OfflineSigner, Registry } from "@cosmjs/proto-signing";
import { msgTypes } from './registry';
import { IgniteClient } from "../client"
import { MissingWalletError } from "../helpers"
import { Api } from "./rest";
import { MsgLanguage } from "./types/entropy/ml/tx";
import { MsgCtrl } from "./types/entropy/ml/tx";
import { MsgGenerate } from "./types/entropy/ml/tx";
import { MsgInpaint } from "./types/entropy/ml/tx";


export { MsgLanguage, MsgCtrl, MsgGenerate, MsgInpaint };

type sendMsgLanguageParams = {
  value: MsgLanguage,
  fee?: StdFee,
  memo?: string
};

type sendMsgCtrlParams = {
  value: MsgCtrl,
  fee?: StdFee,
  memo?: string
};

type sendMsgGenerateParams = {
  value: MsgGenerate,
  fee?: StdFee,
  memo?: string
};

type sendMsgInpaintParams = {
  value: MsgInpaint,
  fee?: StdFee,
  memo?: string
};


type msgLanguageParams = {
  value: MsgLanguage,
};

type msgCtrlParams = {
  value: MsgCtrl,
};

type msgGenerateParams = {
  value: MsgGenerate,
};

type msgInpaintParams = {
  value: MsgInpaint,
};


export const registry = new Registry(msgTypes);

const defaultFee = {
  amount: [],
  gas: "200000",
};

interface TxClientOptions {
  addr: string
	prefix: string
	signer?: OfflineSigner
}

export const txClient = ({ signer, prefix, addr }: TxClientOptions = { addr: "http://localhost:26657", prefix: "cosmos" }) => {

  return {
		
		async sendMsgLanguage({ value, fee, memo }: sendMsgLanguageParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgLanguage: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgLanguage({ value: MsgLanguage.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgLanguage: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgCtrl({ value, fee, memo }: sendMsgCtrlParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgCtrl: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgCtrl({ value: MsgCtrl.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgCtrl: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgGenerate({ value, fee, memo }: sendMsgGenerateParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgGenerate: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgGenerate({ value: MsgGenerate.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgGenerate: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgInpaint({ value, fee, memo }: sendMsgInpaintParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgInpaint: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgInpaint({ value: MsgInpaint.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgInpaint: Could not broadcast Tx: '+ e.message)
			}
		},
		
		
		msgLanguage({ value }: msgLanguageParams): EncodeObject {
			try {
				return { typeUrl: "/blockentropy.entropy.ml.MsgLanguage", value: MsgLanguage.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgLanguage: Could not create message: ' + e.message)
			}
		},
		
		msgCtrl({ value }: msgCtrlParams): EncodeObject {
			try {
				return { typeUrl: "/blockentropy.entropy.ml.MsgCtrl", value: MsgCtrl.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgCtrl: Could not create message: ' + e.message)
			}
		},
		
		msgGenerate({ value }: msgGenerateParams): EncodeObject {
			try {
				return { typeUrl: "/blockentropy.entropy.ml.MsgGenerate", value: MsgGenerate.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgGenerate: Could not create message: ' + e.message)
			}
		},
		
		msgInpaint({ value }: msgInpaintParams): EncodeObject {
			try {
				return { typeUrl: "/blockentropy.entropy.ml.MsgInpaint", value: MsgInpaint.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgInpaint: Could not create message: ' + e.message)
			}
		},
		
	}
};

interface QueryClientOptions {
  addr: string
}

export const queryClient = ({ addr: addr }: QueryClientOptions = { addr: "http://localhost:1317" }) => {
  return new Api({ baseURL: addr });
};

class SDKModule {
	public query: ReturnType<typeof queryClient>;
	public tx: ReturnType<typeof txClient>;
	
	public registry: Array<[string, GeneratedType]> = [];

	constructor(client: IgniteClient) {		
	
		this.query = queryClient({ addr: client.env.apiURL });		
		this.updateTX(client);
		client.on('signer-changed',(signer) => {			
		 this.updateTX(client);
		})
	}
	updateTX(client: IgniteClient) {
    const methods = txClient({
        signer: client.signer,
        addr: client.env.rpcURL,
        prefix: client.env.prefix ?? "cosmos",
    })
	
    this.tx = methods;
    for (let m in methods) {
        this.tx[m] = methods[m].bind(this.tx);
    }
	}
};

const Module = (test: IgniteClient) => {
	return {
		module: {
			BlockentropyEntropyMl: new SDKModule(test)
		},
		registry: msgTypes
  }
}
export default Module;